services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    rootDir: backend

  - type: static
    name: frontend
    rootDir: frontend
